version: '3'
services:
  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5678:5432"
    environment:
      - POSTGRES_PASSWORD=secret
  web:
    image: doerfli/rss-mock-server:0.2.0
    ports:
      - "3000:3000"
    depends_on:
      - db
    