version: '3'
services:
  db:
    image: postgres:11-alpine
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5678:5432"
  web:
    image: doerfli/rss-mock-server:0.1.0
    ports:
      - "3000:3000"
    depends_on:
      - db
    