name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Extract branch name
      run:  echo '${GITHUB_REF}' | sed 's/^refs\/heads\/\(.*\)$/\1/g'
      env:
          BRANCH: $
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag doerfli/rss-mock-server:${BRANCH}